version: '3.7'
services:
  postgres:
    image: ${POSTGRES_IMAGE:-postgres:12.6}
    hostname: postgres
    environment:
      # loading certs requires a non-default PGDATA, even though we don't use certs
      - PGDATA=/var/lib/postgresql/data/pgdata
      - PGPORT=5432
      - POSTGRES_USER=puppetdb
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_DB=puppetdb
      # Testing specific variables needed to bootstrap cert preloading
      - CERT_VOLUME=puppetdb-postgres
    healthcheck:
      # existence check for puppetdb database
      test: [ 'CMD-SHELL', "psql --username=puppetdb puppetdb -c ''" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 90s
    volumes:
      - puppetdb-postgres:/var/lib/postgresql/data
      - ./postgres-custom:/docker-entrypoint-initdb.d
    restart: always
    expose:
      - 5432

volumes:
  puppetdb-postgres:
    # Testing specific variable needed to bootstrap cert preloading
    # Added for documentation even though oss doesn't currently use certs
    labels:
      com.puppet.certs.uid: 999
      com.puppet.certs.gid: 999
